version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"   # Puerto para el backend PHP
      - "5173:5173"   # Puerto para Vite
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=leonhardus
      - DB_USERNAME=root
      - DB_PASSWORD=Rouse17*
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Rouse17*
      - MYSQL_DATABASE=leonhardus
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
